# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Download"
  pageRef = "download"
  weight = 20

[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 30

[[main]]
  name = "Manual"
  url = "https://openmopac.github.io/Manual"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/openmopac/mopac"
  weight = 60
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  name = "YouTube"
  url = "https://www.youtube.com/@OpenMOPAC"
  weight = 70
  [main.params]
    icon = "youtube"
    showName = false
    target = "_blank"

[[main]]
  name = "Email"
  url = "mailto:openmopac@gmail.com"
  weight = 80
  [main.params]
    icon = "email"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
